### ISSUE TITLE
关于一个组件多路由使用需要缓存

### ISSUE THREAD

**Issue by Muspcn** [wurencaideli/dumogu-admin#2]
请教下大佬这个用法创建后使用push打开不回去创建组件是啥原因
vite4 vue3.2

              <router-view>
                <template #default="{ Component, route }">
                  <keep-alive>
                    <component :is="formatComponentInstance(Component,route)"/>
                  </keep-alive>
                </template>
              </router-view>

​const formatComponentInstance = (Component: any, route: any) => {
let wrapper;
if (Component) {
const wrapperName = route.name;
if (wrapperMap.has(wrapperName)) {
console.log("从缓存中读取")
wrapper = wrapperMap.get(wrapperName);
} else {
wrapper = {
name: wrapperName,
render() {
return h(Component);
},
};
wrapperMap.set(wrapperName, wrapper);
console.log("创建全新组件")
}
return h(wrapper);
}
}
​
​不知道为啥返回不了，可以创建就是不能打开原来的

**Comment by wurencaideli** [comment]
你这个意思是关于一个组件多路由使用需要缓存的需求没有实现？
我有点没了解是哈意思，以下是以我的理解：
确定每个路由对应的组件名是不同的？你这个wrapperName不能用route.name吧，这样写你在配置路由的时候写不一样的应该也行，既然是不一样的路由，为啥不用路由路径当作组件名称，const wrapperName = route.path;
而且<keep-alive>组件也没见你用include来区别那些需要缓存，那些不需要缓存。或许你不需要<component :is="formatComponentInstance(Component,route)"/>，直接<component :is="Component"/>

或者你是设置路由的时候出问题了，路由会自带缓存，这是官方原话。
const routes = [
  // 动态字段以冒号开始
  { path: '/users/:id', component: User },
]
使用带有参数的路由时需要注意的是，当用户从 /users/johnny 导航到 /users/jolyne 时，相同的组件实例将被重复使用。

**Comment by Muspcn** [comment]
谢谢
